### ISSUE TITLE
Hard to debug failing request

### ISSUE THREAD

**Issue by jkimbo** [gocardless/gocardless-pro-go#5]
It's quite hard to debug a request that was returning a 422 error because the error that is returned (in this case from the billing create service) is a [`responseError`](https://github.com/gocardless/gocardless-pro-go/blob/c90aa6a9021d3e5dc6e7ceb3eb73bcfd8e9f2516/retries.go#L63) which is not exported from the library. 

To help with debugging it would be great if either the `responseError` should be exported (so that the cause can be logged) or the method should return an `APIError` instead.

**Comment by vdandugc** [comment]
this is now fixed in #4 , especially [this](https://github.com/gocardless/gocardless-pro-go#error-handling).
